version: '3.8'

services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: bevar-ukraine-website
    restart: unless-stopped
    environment:
      - NODE_ENV=production
